// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using MiniLogistics.Infrastructure.Persistence;

#nullable disable

namespace MiniLogistics.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(MiniLogisticsDbContext))]
    [Migration("20260715090000_AddPartnerApiProductionHardening")]
    partial class AddPartnerApiProductionHardening
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
        }
    }
}
