<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
    <OpenApiGenerateDocuments>true</OpenApiGenerateDocuments>
    <OpenApiDocumentsDirectory>$(MSBuildProjectDirectory)\..\..\docs</OpenApiDocumentsDirectory>
    <OpenApiGenerateDocumentsOptions>--file-name partner-api --document-name v1</OpenApiGenerateDocumentsOptions>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" Version="10.0.0" />
    <PackageReference Include="Microsoft.OpenApi" Version="2.11.0" />
    <PackageReference Include="Microsoft.Extensions.ApiDescription.Server" Version="10.0.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="StackExchange.Redis" Version="3.0.17" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MiniLogistics.Application\MiniLogistics.Application.csproj" />
    <ProjectReference Include="..\MiniLogistics.Infrastructure\MiniLogistics.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\images\landing\" />
  </ItemGroup>

  <Target Name="RenamePartnerOpenApiDocument" AfterTargets="GenerateOpenApiDocuments">
    <Move SourceFiles="$(OpenApiDocumentsDirectory)\partner-api.json"
          DestinationFiles="$(OpenApiDocumentsDirectory)\partner-api.openapi.json"
          Condition="Exists('$(OpenApiDocumentsDirectory)\partner-api.json')" />
  </Target>

</Project>
